CREATE TABLE SubContractor(
  SID SERIAL PRIMARY KEY,
  S_Lname VARCHAR(100),
  S_Fname VARCHAR(100),
  Salary INTEGER
);

CREATE TABLE Builder(
   BID SERIAL PRIMARY KEY,
   B_Lname VARCHAR(100),
   B_Fname VARCHAR(100),
   License INTEGER
);

CREATE TABLE Neighborhood(
  NID SERIAL PRIMARY KEY,
  N_Name VARCHAR(100),
  City VARCHAR(100)
);

CREATE TABLE HireInfo(
  BID INTEGER,
  SID INTEGER,
  HireDate DATE,
  PRIMARY KEY (BID,SID),
  CONSTRAINT fk_bid
  	FOREIGN KEY (BID)
  		REFERENCES Builder(BID),
  CONSTRAINT fk_sid
  	FOREIGN KEY (SID)
  		REFERENCES SubContractor(SID)
);

CREATE TABLE House(
  HID SERIAL PRIMARY KEY,
  H_Name VARCHAR(100),
  FinishDate DATE,
  Price INTEGER,
  BID INTEGER,
  NID INTEGER,
  CONSTRAINT fk_bid
  	FOREIGN KEY (BID)
  		REFERENCES Builder(BID),
  CONSTRAINT fk_nid
  	FOREIGN KEY (NID)
  		REFERENCES Neighborhood(NID)
);